import React, { useState } from 'react';
import { ArrowRight, Check, KeyRound, LockKeyhole, Mail, MessageCircle, ShieldCheck } from 'lucide-react';
import { withBase } from './basePath.js';

export default function AccountRecoveryPage() {
  const [mode, setMode] = useState('id');
  const [done, setDone] = useState(false);
  const submit = (event) => { event.preventDefault(); setDone(true); };
  return <div className="recovery-page"><header><small>ACCOUNT HELP</small><h1>로그인 정보를<br />안전하게 확인하세요</h1><p>가입한 이메일 확인과 비밀번호 재설정 절차를 안내합니다.</p></header><div className="recovery-shell"><section className="recovery-card"><div className="recovery-tabs"><button className={mode === 'id' ? 'active' : ''} onClick={() => { setMode('id'); setDone(false); }}><Mail /> 아이디 찾기</button><button className={mode === 'password' ? 'active' : ''} onClick={() => { setMode('password'); setDone(false); }}><KeyRound /> 비밀번호 재설정</button></div>{done ? <div className="recovery-done"><span><Check /></span><h2>확인 요청을 접수했습니다</h2><p>입력한 정보가 가입 정보와 일치하면 인증 안내를 보내드립니다. 안내를 받지 못하면 메디헬퍼스 고객센터로 문의해주세요.</p><button className="button primary" onClick={() => setDone(false)}>다시 확인하기</button></div> : <form onSubmit={submit}><span className="recovery-icon">{mode === 'id' ? <Mail /> : <LockKeyhole />}</span><h2>{mode === 'id' ? '가입한 이메일 찾기' : '비밀번호 재설정'}</h2><p>{mode === 'id' ? '가입할 때 입력한 이름과 휴대전화로 계정을 확인합니다.' : '가입한 이메일로 본인 확인 링크를 요청합니다.'}</p>{mode === 'id' ? <><label><span>이름·담당자명</span><input required placeholder="이름을 입력해주세요" /></label><label><span>휴대전화</span><input required type="tel" placeholder="010-0000-0000" /></label></> : <label><span>가입 이메일</span><input required type="email" placeholder="example@email.com" /></label>}<button className="button primary full" type="submit">인증 안내 요청 <ArrowRight /></button></form>}</section><aside className="recovery-help"><ShieldCheck /><h3>계정 보안 안내</h3><ul><li>인증번호나 비밀번호를 타인에게 알려주지 마세요.</li><li>의사·병원 회원 유형이 달라도 같은 로그인 도움을 이용합니다.</li><li>계정 정보가 기억나지 않으면 담당자가 본인 확인을 도와드립니다.</li></ul><a href="tel:0513425463"><MessageCircle /> 051-342-5463</a><a href="mailto:hr@medihelpers.co.kr">hr@medihelpers.co.kr</a><a className="recovery-login" href={withBase('/login')}>로그인 화면으로 돌아가기</a></aside></div></div>;
}
