import React, { useMemo, useState } from 'react';
import { AlertCircle, ArrowRight, BarChart3, Building2, Check, CheckCircle2, CircleHelp, FileCheck2, Heart, Mail, MessageCircle, Phone, ShieldCheck, SlidersHorizontal, Stethoscope, UserRound } from 'lucide-react';

const doctorPriorities=[['schedule','근무일·당직'],['pay','보수·인센티브'],['commute','지역·통근'],['scope','진료 범위'],['environment','병원 환경']];
const hospitalPriorities=[['specialty','전문과목·경력'],['skills','주요 진료·술기'],['region','희망 지역'],['workType','근무형태'],['available','입사 가능 시점']];
const read=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
const itemId=(role,item)=>role==='doctor'?item.id:item.code;
const itemName=(role,item)=>role==='doctor'?item.hospital:`${item.code} · ${item.dept}`;
const toneLabel={match:'공개 확인',review:'협의 필요',info:'추가 확인'};
function track(event,detail={}){const records=read('medihelpers_conversion_events');records.push({event,detail,path:window.location.pathname,createdAt:new Date().toISOString()});localStorage.setItem('medihelpers_conversion_events',JSON.stringify(records.slice(-100)))}
function Go({to,onNavigate,children}){return <a href={to} onClick={(e)=>{e.preventDefault();onNavigate(to)}}>{children}</a>}

function rowsFor(role,items){
 if(role==='doctor')return[
  ['schedule','근무일·당직',items.map(x=>[x.schedule,x.schedule.includes('4')?'match':'review'])],
  ['pay','보수·인센티브',items.map(x=>[x.pay,x.pay.includes('협의')?'review':'match'])],
  ['commute','지역·통근',items.map(x=>[x.location,'info'])],
  ['scope','진료 범위',items.map(x=>[x.focus,'info'])],
  ['environment','병원 환경',items.map(x=>[`${x.facilityType} · ${x.scale}`,'info'])]
 ];
 return[
  ['specialty','전문과목·경력',items.map(x=>[`${x.dept} · ${x.career}`,x.verified?'match':'review'])],
  ['skills','주요 진료·술기',items.map(()=>['상세 확인 필요','review'])],
  ['region','희망 지역',items.map(x=>[x.region,'info'])],
  ['workType','가능한 근무형태',items.map(x=>[x.preference,'info'])],
  ['available','입사 가능 시점',items.map(x=>[x.available,x.available.includes('즉시')?'match':'review'])],
  ['verified','자격·경력 확인',items.map(x=>[x.verified?'기본 확인 완료':'확인 중',x.verified?'match':'review'])]
 ];
}

function Picker({role,items,favorites,selected,setSelected,onNavigate}){
 const[notice,setNotice]=useState('');
 const ordered=useMemo(()=>[...items].sort((a,b)=>Number(favorites.includes(itemId(role,b)))-Number(favorites.includes(itemId(role,a)))),[items,favorites,role]);
 const toggle=(id)=>{setNotice('');setSelected(cur=>{if(cur.includes(id))return cur.filter(x=>x!==id);if(cur.length>=3){setNotice('한 번에 최대 3개까지 비교할 수 있습니다.');return cur}return[...cur,id]})};
 return <div className="report-picker"><div className="report-block-head"><div><small>STEP 01</small><h2>{role==='doctor'?'비교할 병원을 선택하세요':'비교할 의료인 후보를 선택하세요'}</h2><p>찜한 항목을 먼저 보여드립니다. 2~3개를 선택하면 비교 리포트가 열립니다.</p></div><span>{selected.length}/3 선택</span></div><div className="report-choice-grid">{ordered.map(item=>{const id=itemId(role,item),active=selected.includes(id),favorite=favorites.includes(id);return <button type="button" className={`report-choice ${active?'selected':''}`} onClick={()=>toggle(id)} key={id} aria-pressed={active}><span className="report-choice-check">{active?<Check/>:role==='doctor'?<Building2/>:<UserRound/>}</span><span><small>{role==='doctor'?`${item.dept} · ${item.location}`:`${item.career} · ${item.region}`}</small><strong>{itemName(role,item)}</strong><em>{role==='doctor'?`${item.schedule} · ${item.pay}`:`${item.preference} · ${item.available}`}</em></span>{favorite&&<i><Heart fill="currentColor"/> 찜</i>}</button>})}</div>{notice&&<p className="report-limit"><AlertCircle/>{notice}</p>}{!favorites.length&&<div className="report-tip"><CircleHelp/><span>아직 찜한 항목이 없습니다. 여기서 바로 선택하거나 <Go to={role==='doctor'?'/jobs':'/talent'} onNavigate={onNavigate}>목록에서 먼저 둘러보기</Go>도 가능합니다.</span></div>}</div>
}

function Matrix({role,items,priorities}){const rows=rowsFor(role,items).sort((a,b)=>{const ai=priorities.indexOf(a[0]),bi=priorities.indexOf(b[0]);if(ai===-1&&bi===-1)return 0;if(ai===-1)return 1;if(bi===-1)return-1;return ai-bi});return <div className="report-result"><div className="report-block-head"><div><small>STEP 03 · MATCHING REPORT</small><h2>선택 조건을 나란히 확인했습니다</h2><p>종합점수 대신 잘 맞는 이유와 헤드헌터가 확인할 질문을 함께 보여드립니다.</p></div><div className="report-legend"><span className="match">공개 확인</span><span className="review">협의 필요</span><span className="info">추가 확인</span></div></div><div className={`report-table columns-${items.length}`}><div className="report-table-head"><strong>비교 조건</strong>{items.map(item=><div key={itemId(role,item)}><small>{role==='doctor'?item.dept:item.code}</small><b>{itemName(role,item)}</b></div>)}</div>{rows.map(([key,label,cells])=><div className={`report-table-row ${priorities.includes(key)?'priority':''}`} key={key}><strong>{priorities.includes(key)&&<><span className="report-priority-rank">{priorities.indexOf(key)+1}</span><SlidersHorizontal/></>}{label}</strong>{cells.map(([value,tone],i)=><div key={`${key}-${i}`}><span className={`report-status ${tone}`}>{tone==='match'?<CheckCircle2/>:tone==='review'?<AlertCircle/>:<CircleHelp/>}{toneLabel[tone]}</span><p>{value}</p></div>)}</div>)}</div><div className="report-insights">{items.map(item=>{const good=role==='doctor'?`${item.schedule} 근무와 ${item.focus} 환경을 우선 확인할 수 있습니다.`:`${item.dept} ${item.career} 경력과 ${item.region} 선호가 공개되어 있습니다.`;const question=role==='doctor'?`${item.pay.includes('협의')?'정확한 보수·인센티브':'당직 빈도와 실제 진료 범위'}를 병원에 확인해야 합니다.`:'세부 술기, 희망 보수와 실제 근무 가능 일정을 후보자 동의 후 확인해야 합니다.';return <article key={itemId(role,item)}><div><span>{role==='doctor'?<Building2/>:<UserRound/>}</span><h3>{itemName(role,item)}</h3></div><dl><div><dt>잘 맞는 부분</dt><dd>{good}</dd></div><div><dt>확인할 질문</dt><dd>{question}</dd></div></dl></article>})}</div></div>}

function Consultation({role,items,priorities}){
 const[submitted,setSubmitted]=useState(null),options=role==='doctor'?doctorPriorities:hospitalPriorities,labels=priorities.map((id,index)=>{const label=options.find(([optionId])=>optionId===id)?.[1];return label?(index+1)+'\uC21C\uC704 '+label:null}).filter(Boolean),names=items.map(x=>itemName(role,x));
 const defaultQuestion=role==='doctor'?'급여·당직·진료 범위 중 공개되지 않은 조건을 확인해주세요.':'후보자의 세부 술기·희망 보수·입사 가능 일정을 확인해주세요.';
 const mailBody=encodeURIComponent(`${role==='doctor'?'의료인':'병원'} 매칭 리포트 검토 요청\n비교 대상: ${names.join(', ')}\n중요 조건: ${labels.join(', ')||'상담 중 결정'}\n확인 요청: ${defaultQuestion}`);
 const submit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries()),id=`MH-R-${String(Date.now()).slice(-6)}`,records=read('medihelpers_consultations');records.push({id,role,topic:'매칭 리포트 검토',context:'matching-report',report:{itemIds:items.map(x=>itemId(role,x)),itemNames:names,priorities:labels,question:data.question},status:'new',createdAt:new Date().toISOString(),...data});localStorage.setItem('medihelpers_consultations',JSON.stringify(records));track('matching_report_consultation',{role,itemCount:items.length,priorities:labels});setSubmitted(id)};
 if(submitted)return <div className="report-consult-success"><span><CheckCircle2/></span><small>상담번호 {submitted}</small><h2>비교 결과와 확인 질문을 저장했습니다</h2><p>현재 시범 운영 화면에서는 담당자 자동 알림 연결 전입니다. 아래 이메일 전송 또는 전화 상담을 이용하면 바로 확인할 수 있습니다.</p><div><a className="button primary" href={`mailto:hr@medihelpers.co.kr?subject=${encodeURIComponent('[메디헬퍼스] 매칭 리포트 검토 요청')}&body=${mailBody}`}><Mail/> 이메일로 전송</a><a className="button outline" href="tel:0513425463"><Phone/> 051-342-5463</a></div></div>;
 return <div className="report-consult-card"><div className="report-consult-copy"><span className="section-kicker">HUMAN REVIEW</span><h2>혼자 비교하고 끝내지 마세요.</h2><p>확인이 필요한 조건은 메디헬퍼스가 직접 알아보겠습니다.</p><div className="advisor-preview"><span><MessageCircle/></span><div><small>헤드헌터에게 함께 전달됩니다</small><strong>{names.join(' · ')}</strong><p>{labels.length?`${labels.join(' · ')} 조건을 중요하게 선택`:'중요 조건은 상담 중 함께 정리'}</p></div></div></div><form onSubmit={submit}><div className="form-grid"><label><span>{role==='doctor'?'연락받을 이름':'병원명·담당자'} *</span><input required name="name"/></label><label><span>전화번호 *</span><input required name="phone" type="tel" placeholder="010-0000-0000"/></label></div><div className="form-grid"><label><span>편한 연락 시간</span><select name="contactTime" defaultValue="오후"><option>오전</option><option>오후</option><option>저녁</option><option>상관없음</option></select></label><label><span>연락 방법</span><select name="contactMethod" defaultValue="전화"><option>전화</option><option>문자</option></select></label></div><label><span>가장 궁금한 조건</span><textarea name="question" rows="3" defaultValue={defaultQuestion}/></label><label className="consent"><input required type="checkbox" name="privacy" value="agreed"/><span>상담을 위한 개인정보 수집·이용에 동의합니다. 비교 대상과 선택 조건이 상담 요청에 함께 포함됩니다.</span></label><button className="button primary full" type="submit">이 비교 결과를 헤드헌터와 함께 검토하기 <ArrowRight/></button><p className="form-note"><ShieldCheck/> 의료인 정보는 본인 동의 없이 병원에 공개하지 않습니다.</p></form></div>
}

export default function MatchingReportPage({route,jobs,talent,onNavigate}){
 const params=new URLSearchParams(route.split('?')[1]||''),initial=params.get('role')==='hospital'?'hospital':'doctor';
 const[role,setRole]=useState(initial),[selected,setSelected]=useState(()=>read(initial==='hospital'?'medihelpers_saved_talent':'medihelpers_saved_jobs').slice(0,3)),[priorities,setPriorities]=useState(()=>initial==='hospital'?['specialty','available']:['schedule','pay']),[notice,setNotice]=useState('');
 const items=role==='doctor'?jobs:talent,favorites=read(role==='doctor'?'medihelpers_saved_jobs':'medihelpers_saved_talent'),selectedItems=selected.map(id=>items.find(x=>itemId(role,x)===id)).filter(Boolean),options=role==='doctor'?doctorPriorities:hospitalPriorities;
 const changeRole=next=>{setRole(next);setSelected(read(next==='doctor'?'medihelpers_saved_jobs':'medihelpers_saved_talent').slice(0,3));setPriorities(next==='doctor'?['schedule','pay']:['specialty','available']);setNotice('')};
 const togglePriority=id=>{setNotice('');setPriorities(cur=>{if(cur.includes(id))return cur.filter(x=>x!==id);if(cur.length>=3){setNotice('중요 조건은 최대 3개까지 선택할 수 있습니다.');return cur}return[...cur,id]})};
 return <><section className="page-hero matching-hero"><div className="page-hero-inner matching-intro"><span className="eyebrow"><BarChart3/> MEDIHELPERS MATCHING REPORT</span><h1>순위가 아니라,<br/>나에게 맞는 이유를 봅니다</h1><p>찜한 병원이나 의료인 후보를 조건별로 비교하고, 확인이 필요한 부분은 전담 헤드헌터에게 그대로 전달하세요.</p><div className="matching-role-tabs"><button className={role==='doctor'?'active':''} onClick={()=>changeRole('doctor')}><Stethoscope/> 의료인 · 병원 비교</button><button className={role==='hospital'?'active':''} onClick={()=>changeRole('hospital')}><Building2/> 병원 · 후보 비교</button></div></div></section><section className="section report-workspace"><Picker role={role} items={items} favorites={favorites} selected={selected} setSelected={setSelected} onNavigate={onNavigate}/><div className="priority-panel"><div className="report-block-head"><div><small>STEP 02</small><h2>가장 중요한 조건을 골라주세요</h2><p>선택한 순서대로 1·2·3순위가 되며, 리포트에서 먼저 확인합니다.</p></div></div><div className="priority-chips">{options.map(([id,label])=><button type="button" key={id} className={priorities.includes(id)?'selected':''} onClick={()=>togglePriority(id)}><SlidersHorizontal/>{label}{priorities.includes(id)&&<span className="priority-rank">{priorities.indexOf(id)+1}순위</span>}</button>)}</div>{notice&&<p className="report-limit"><AlertCircle/>{notice}</p>}</div>{selectedItems.length>=2?<><Matrix role={role} items={selectedItems} priorities={priorities}/><Consultation role={role} items={selectedItems} priorities={priorities}/></>:<div className="report-empty"><FileCheck2/><h2>2개 이상 선택하면 비교 리포트가 열립니다</h2><p>절대적인 순위나 단일 점수 없이 조건별 차이와 확인할 질문을 정리합니다.</p></div>}</section></>
}